### ISSUE TITLE
Subfolder attachment paths are broken

### ISSUE THREAD

**Issue by Moyf** [sandorex/nuke-orphans-plugin#10]
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/4c6f1b8c-60f2-4792-85b6-50fb9714b9a0)

I just created a sandbox vault to test, and this file is not used in any note.

But this plug-in just said no orphaned attachment found 🤔
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/2007f4c7-f262-48b0-86b7-63582e44a0fb)

**Comment by sandorex** [comment]
When you use the "Trash orphaned attachments" option it looks only in attachments folder as defined in the settings
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/18004075/d252ecac-29f8-4c7c-b36f-a1ba32847813)

try using "Trash orphaned files" option instead
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/18004075/408431ec-55d6-4a52-83c0-c657d44ffe5e)

**Comment by Moyf** [comment]
Oh Hi, thanks for replying!

Yeah what I want is only remove my attachments, and I did another test.

I set the OB's assets folder to "subfolder/Assets"
And in Plugin I tried "Assets" and "./Assets"

I pasted 3 images in note, and deleted one of 'em, then run the command, but it says no  orphaned file found.
<img width="1104" alt="image" src="https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/0fc461f2-0825-4c21-9ea4-b6b627fbc127">

Did I miss something?

Here is a gif:
![demo](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/9f2ee42d-bccb-4fd5-8ed0-f591d055acd8)


(BTW it also works well for me before, so strange 🤔)

**Comment by Moyf** [comment]
<img width="595" alt="image" src="https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/abfcc5cc-7647-4a4a-8583-e8f194a35fc7">

Oh and the "orphaned files" command works well, but I only want to remove the orphaned images which is not used anymore, rather than .md files.

I've tried many similar plugins but this one is the most convenience and good to use <3

**Comment by sandorex** [comment]
You are using a relative attachments folder (`Assets`) not a global one right?

I think i broke the subfolder attachments, it uses attachments path as a global one, ill look it into it as soon as i can

Thank you for submitting a bug report though :smile:

**Comment by Moyf** [comment]
> You are using a relative attachments folder (`Assets`) not a global one right?
> 
> I think i broke the subfolder attachments when i fixed the plugin few updates ago as i had to rework big chunk of it, now it uses attachments path as a global one, ill see if i can fix it but i cannot promise any ETA
> 
> Thank you for submitting a bug report though 😄

Oh Yes!
Roger that, thank you!

No problem, take your time!

**Comment by sandorex** [comment]
Im pretty sure i fixed it, but i'd appreciate it if you could test it out yourself (you could use [BRAT](https://tfthacker.com/brat-quick-guide))

Im not gonna release it right now as i have not extensively tested it

**Comment by Moyf** [comment]
> Im pretty sure i fixed it, but i'd appreciate it if you could test it out yourself (you could use [BRAT](https://tfthacker.com/brat-quick-guide))
> 
> Im not gonna release it right now as i have not extensively tested it

WOW so fast!
I appreciate it so much, you are AMAZING!



Well about the BRAT, I tried to install this plugin from it:
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/49efc7b8-6036-4260-89fc-12219212889d)

But how can I be sure I installed the correct version?
Or should I remove the old version then just use BRAT to install again?

**Comment by Moyf** [comment]
I'm sorry but it seems that I failed to install the newest beta version through BRAT 😢 
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/507594e0-140a-4b99-af33-1d846fa7440a)

I uninstalled the old version and install like this:
> Well about the BRAT, I tried to install this plugin from it: ![image](https://private-user-images.githubusercontent.com/4013062/296600075-49efc7b8-6036-4260-89fc-12219212889d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzYzMTQsIm5iZiI6MTcwNTMzNjAxNCwicGF0aCI6Ii80MDEzMDYyLzI5NjYwMDA3NS00OWVmYzdiOC02MDM2LTQyNjAtODlmYy0xMjIxOTIxMjg4OWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTYyNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZhOTRiMTgxYmUzMjQ2MzI4YjNkY2YwYmIyZjFiNmE4Y2EwZGU0NDU1MGJmZjA0ZmYyOWM5MWYwODY5ZDUzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BJiU6vSb9lSL4tqXoCXP-GBE8qbDCY1XMXG_fdw6W6s)

![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/18e96ec3-0ef1-4b55-89b3-bb886c2b747f)

But still 1.2.4 and no new options show up

**Comment by sandorex** [comment]
Ill update the README for manual installation later here's a zip that you can install manually by just putting it in `.obsidian/plugins/nuke-orphans` inside your vault
[Uploading nuke-orphans-plugin.zip…]()

**Comment by Moyf** [comment]
> ~Ill update the README for manual installation later here's a zip that you can install manually by just putting it in `.obsidian/plugins/nuke-orphans` inside your vault [nuke-orphans-plugin.zip](https://github.com/sandorex/nuke-orphans-plugin/files/13949387/nuke-orphans-plugin.zip)~
> 
> I will just release this today, so you can just go and update normally

OHHHHHHHH It worked again!!
Thanks so much! Love it  <3

You're a fantastic developer!!
