### ISSUE TITLE
Orphaned attachments are not really orphaned

### ISSUE THREAD

**Issue by Seraphli** [sandorex/nuke-orphans-plugin#3]
![image](https://user-images.githubusercontent.com/1586755/202183972-2f86f96f-c5f0-450e-bcfd-330ae1c03716.png)

**Comment by sandorex** [comment]
Ill look into it, can't promise any ETA though

**Comment by sandorex** [comment]
I have not been able to reproduce this, please provide a minimal vault where i can reproduce the bug otherwise i will have to close this

**Comment by Seraphli** [comment]
I just tested it and the issue disappear. I don't know if a conflict with other plugins caused this. Anyway, the problem is solved.
