### ISSUE TITLE
Option to add multiple folders for attachments

### ISSUE THREAD

**Issue by himanshugoswamiii** [sandorex/nuke-orphans-plugin#4]
**Feature Request**

I've multiple folders for attachments like :
Attachments : for Images/Videos
Excalidraw : for excalidraw files

Currently I'm able to set only one folder in settings

Is it possible to set two of them, so the plugin scan both of them

**Comment by sandorex** [comment]
This would require more work than i have time for, if someone want to contribute feel free to do so

**Comment by sandorex** [comment]
Turns out there was nothing broken with the plugin so i had some time to add this quickly in [v1.2.1](https://github.com/sandorex/nuke-orphans-plugin/releases/tag/1.2.2) enjoy!
