### ISSUE TITLE
Images pasted to canvas are removed

### ISSUE THREAD

**Issue by dustyghost** [sandorex/nuke-orphans-plugin#7]
When using the Nuke Orphans: Trash orphaned attachments it does not consider that an image is on a Canvas, 

![image](https://github.com/sandorex/nuke-orphans-plugin/assets/10135321/93283515-377f-4360-89a4-6967e2dec430)
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/10135321/7b40dcea-cc70-4812-902b-1c75be1e9d56)

**Comment by sandorex** [comment]
Thanks for submitting the issue ill look into it

**Comment by sandorex** [comment]
Unfortunately the API between notes and canvas is not consistent so this may take a while to fix..

**Comment by dustyghost** [comment]
No rush from me :)

**Comment by sandorex** [comment]
I will release the next version shortly

**Comment by dustyghost** [comment]
Thank you for your prompt fix, this is now working as expected.
