### ISSUE TITLE
Error in folder naming on PNG paste

### ISSUE THREAD

**Issue by benpla** [sandorex/nuke-orphans-plugin#8]
Hallo,

I wish to convert every PNG without further renaming or movement with the following settings:
<img width="790" alt="grafik" src="https://github.com/sandorex/nuke-orphans-plugin/assets/38682514/9ecb1192-1f12-49a0-b93d-f3e171454cbc">

On PNG paste the following Error occurs:
<img width="345" alt="grafik" src="https://github.com/sandorex/nuke-orphans-plugin/assets/38682514/5e806e7c-85e6-417b-b2cb-f52094e69ea1">

and the Console shows:
<img width="548" alt="grafik" src="https://github.com/sandorex/nuke-orphans-plugin/assets/38682514/b9bb5f3f-f0af-4400-b864-2fff1f69e00b">

Looks like a clash in the folder name?

**Comment by sandorex** [comment]
Wrong repository, this repo is for nuke-orphans plugin

**Comment by benpla** [comment]
Sorry

**Comment by benpla** [comment]
...I use your plugin as well and find it extremely useful. 
Thank you very much for your work!
